# Use root/example as user/password credentials
version: '3.1'

volumes:
  data-db:

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data-db:/data/db

  mongo-express:
    depends_on: 
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo